name: Dependency Review

on:
  pull_request_target:

jobs:
  dependency-review:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run Dependency Review
        uses: github/dependency-review-action@v1
        with:
          # Fail the check if a dependency with a known vulnerability is added
          fail-on-alert: true

          # Optional: Specify allowed licenses
          allowed-licenses: |
            Apache-2.0
            BSD-2-Clause
            BSD-3-Clause
            MIT
            CPOL
