name: Dependency Review

on:
  pull_request:

jobs:
  dependency-review:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run Dependency Review
        uses: actions/dependency-review-action@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
